# Generated by Django 5.2.5 on 2025-08-14 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='created_at',
        ),
    ]
