# Generated by Django 5.2.5 on 2025-08-14 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0002_remove_upload_created_at'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='energyrecord',
            new_name='energy_reco_city_23a8c9_idx',
            old_name='consumption_city_53c369_idx',
        ),
        migrations.RenameIndex(
            model_name='energyrecord',
            new_name='energy_reco_date_c9f056_idx',
            old_name='consumption_date_2fe2fb_idx',
        ),
        migrations.AlterModelTable(
            name='energyrecord',
            table='energy_records',
        ),
        migrations.AlterModelTable(
            name='upload',
            table='uploads',
        ),
    ]
