# Generated by Django 5.2.5 on 2025-08-14 16:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0003_rename_consumption_city_53c369_idx_energy_reco_city_23a8c9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=True,
        ),
    ]
