# Generated by Django 5.2.5 on 2025-08-14 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0004_upload_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='created_at',
            new_name='creat_at',
        ),
    ]
