# Generated by Django 5.2.5 on 2025-08-14 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0005_rename_created_at_upload_creat_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='creat_at',
            new_name='created_at',
        ),
    ]
