# Generated by Django 5.2.5 on 2025-08-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0006_rename_creat_at_upload_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
